//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadIraq.Localization.SourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReadIraq.Localization.SourceFiles.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute data type does not match input.
        /// </summary>
        public static string AttributeDataTypeDoesnotMatchInput {
            get {
                return ResourceManager.GetString("AttributeDataTypeDoesnotMatchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your attribute value has previous value.
        /// </summary>
        public static string AttributeValueIsAlreadyExist {
            get {
                return ResourceManager.GetString("AttributeValueIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Delete the Branch, There Is Offer With Status {0}.
        /// </summary>
        public static string CompanyBranchCannotDelete {
            get {
                return ResourceManager.GetString("CompanyBranchCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Delete the Company, There Is Offer With Status {0}.
        /// </summary>
        public static string CompanyCannotDelete {
            get {
                return ResourceManager.GetString("CompanyCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Delete the Company, you Must Delete the Branches First.
        /// </summary>
        public static string CompanyCannotDeleteBecauseHasingChilds {
            get {
                return ResourceManager.GetString("CompanyCannotDeleteBecauseHasingChilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible Value.
        /// </summary>
        public static string IncompatibleValue {
            get {
                return ResourceManager.GetString("IncompatibleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Broker Code You Entered is not Correct..
        /// </summary>
        public static string MediatorCodeIsNotCorrect {
            get {
                return ResourceManager.GetString("MediatorCodeIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant be deactivate It has related {0}.
        /// </summary>
        public static string ObjectCantBeDeactivate {
            get {
                return ResourceManager.GetString("ObjectCantBeDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to delete. There are Quote Requests that use this {0}.
        /// </summary>
        public static string ObjectCantBeDelete {
            get {
                return ResourceManager.GetString("ObjectCantBeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Is Already Exist.
        /// </summary>
        public static string ObjectIsAlreadyExist {
            get {
                return ResourceManager.GetString("ObjectIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Not Found.
        /// </summary>
        public static string ObjectWasNotFound {
            get {
                return ResourceManager.GetString("ObjectWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Not Approved.
        /// </summary>
        public static string OfferNotApproved {
            get {
                return ResourceManager.GetString("OfferNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offer is not provided for your quote request.
        /// </summary>
        public static string OfferNotMatchWithUser {
            get {
                return ResourceManager.GetString("OfferNotMatchWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Not Found.
        /// </summary>
        public static string PhoneNumberNotFoundInCode {
            get {
                return ResourceManager.GetString("PhoneNumberNotFoundInCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number allowed..
        /// </summary>
        public static string ReachedMaximumNumberAllowed {
            get {
                return ResourceManager.GetString("ReachedMaximumNumberAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your signingup information not correct.
        /// </summary>
        public static string SignUpNotComplete {
            get {
                return ResourceManager.GetString("SignUpNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is already used.
        /// </summary>
        public static string TheCodeIsAlreadyUsed {
            get {
                return ResourceManager.GetString("TheCodeIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Position Is Already Exist.
        /// </summary>
        public static string ThisPositionIsAlreadyExist {
            get {
                return ResourceManager.GetString("ThisPositionIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user ID of the user requesting a quote is required.
        /// </summary>
        public static string UserIdIsRequird {
            get {
                return ResourceManager.GetString("UserIdIsRequird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is expired..
        /// </summary>
        public static string VerificationCodeIsExpired {
            get {
                return ResourceManager.GetString("VerificationCodeIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code isn&apos;t correct.
        /// </summary>
        public static string VerificationCodeIsnotCorrect {
            get {
                return ResourceManager.GetString("VerificationCodeIsnotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code Isn&apos;t valid.
        /// </summary>
        public static string VerificationCodeIsnotValid {
            get {
                return ResourceManager.GetString("VerificationCodeIsnotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can not Add New Draft, You Need To Delete Your Old Draft.
        /// </summary>
        public static string YouCannotAddNewDraft {
            get {
                return ResourceManager.GetString("YouCannotAddNewDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t not do this action.
        /// </summary>
        public static string YouCannotDoThisAction {
            get {
                return ResourceManager.GetString("YouCannotDoThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to modify. Submit a request to modify or wait for approval.
        /// </summary>
        public static string YouCannotEdit {
            get {
                return ResourceManager.GetString("YouCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Do not Have Enough Points.
        /// </summary>
        public static string YouDonotHAveMuchPoints {
            get {
                return ResourceManager.GetString("YouDonotHAveMuchPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email Is Not Confirmed.
        /// </summary>
        public static string YourEmailIsNotConfirmed {
            get {
                return ResourceManager.GetString("YourEmailIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number is not verified.
        /// </summary>
        public static string YourPhoneNumberIsntVerified {
            get {
                return ResourceManager.GetString("YourPhoneNumberIsntVerified", resourceCulture);
            }
        }
    }
}
